version: "3"

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - test-cachet-db:/var/lib/postgresql/data
    restart: always
  cachet:
    build:
      context: .
      args:
        - cachet_ver=2.4
    volumes:
      - ./Cachet:/var/www/html
    ports:
      - 80:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=${APP_KEY:-null}
      - APP_LOG=errorlog
      - APP_ENV=development
      - APP_DEBUG=true
      - DEBUG=true
      # - MAIL_DRIVER=
      # - MAIL_HOST=
      # - MAIL_PORT=
      # - MAIL_USERNAME=
      # - MAIL_PASSWORD=
      # - MAIL_ADDRESS=
      # - MAIL_NAME=
      # - MAIL_ENCRYPTION=
    depends_on:
      - postgres
    restart: on-failure
volumes:
  test-cachet-db:
    driver: local
